#ifndef BRRS_BEACON_PROTOCOL_H
#define BRRS_BEACON_PROTOCOL_H

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/* BRRS control-plane format shared by the coordinator and sensor nodes.
 * All multi-byte fields are little-endian. Frame lengths include the 2-byte
 * IEEE 802.15.4 FCS generated by the DW3000. */
#define BRRS_PROTOCOL_VERSION       2U
#define BRRS_SENSOR_BITMAP_MASK     0x7FU
#define BRRS_MAX_DATA_SLOTS         32U
#define BRRS_SLOT_OWNER_BYTES       ((BRRS_MAX_DATA_SLOTS + 1U) / 2U)
#define BRRS_BEACON_PSDU_BYTES      (27U + BRRS_SLOT_OWNER_BYTES)

/* Common application header. Bytes 0 and 1 remain the IEEE frame-control
 * bytes used by the existing examples. */
enum
{
    BRRS_IDX_SOURCE = 2,
    BRRS_IDX_DEST = 3,
    BRRS_IDX_MSG_TYPE = 4,
    BRRS_IDX_PROTOCOL_VERSION = 5,
    BRRS_IDX_SUPERFRAME_SEQ = 6,
    /* DATA frame: scheduled DATA RMARKER offset from the beacon RMARKER (us).
     * The legacy alias preserves the byte layout for older example modules. */
    BRRS_IDX_DECLARED_SLOT_OFFSET_US = 8,
    BRRS_IDX_TX_TIMESTAMP = BRRS_IDX_DECLARED_SLOT_OFFSET_US,
    BRRS_IDX_DATA_PAYLOAD = 12
};

/* Beacon payload begins at BRRS_IDX_DATA_PAYLOAD. */
enum
{
    BRRS_BEACON_IDX_PREAMBLE_SYMBOLS = BRRS_IDX_DATA_PAYLOAD,
    BRRS_BEACON_IDX_PSDU_BYTES = 14,
    BRRS_BEACON_IDX_DATA_RATE = 16,
    BRRS_BEACON_IDX_ACTIVE_BITMAP = 17,
    BRRS_BEACON_IDX_FIRST_SLOT_OFFSET_US = 18,
    BRRS_BEACON_IDX_SLOT_INTERVAL_US = 20,
    BRRS_BEACON_IDX_SUPERFRAME_PERIOD_US = 22,
    BRRS_BEACON_IDX_SLOT_COUNT = 24,
    BRRS_BEACON_IDX_SLOT_OWNERS = 25
};

typedef struct
{
    uint16_t superframe_seq;
    uint16_t data_preamble_symbols;
    uint16_t data_psdu_bytes;
    uint8_t data_rate;
    uint8_t active_node_bitmap;
    uint16_t first_slot_offset_us;
    uint16_t slot_interval_us;
    uint16_t superframe_period_us;
    uint8_t slot_count;
    uint8_t slot_owner[BRRS_MAX_DATA_SLOTS];
} brrs_beacon_config_t;

static inline void brrs_put_u16_le(uint8_t *dst, uint16_t value)
{
    dst[0] = (uint8_t)(value & 0xFFU);
    dst[1] = (uint8_t)(value >> 8);
}

static inline uint16_t brrs_get_u16_le(const uint8_t *src)
{
    return (uint16_t)((uint16_t)src[0] | ((uint16_t)src[1] << 8));
}

static inline void brrs_put_u32_le(uint8_t *dst, uint32_t value)
{
    dst[0] = (uint8_t)(value & 0xFFU);
    dst[1] = (uint8_t)((value >> 8) & 0xFFU);
    dst[2] = (uint8_t)((value >> 16) & 0xFFU);
    dst[3] = (uint8_t)(value >> 24);
}

static inline uint32_t brrs_get_u32_le(const uint8_t *src)
{
    return (uint32_t)src[0] |
           ((uint32_t)src[1] << 8) |
           ((uint32_t)src[2] << 16) |
           ((uint32_t)src[3] << 24);
}

static inline void brrs_encode_beacon(uint8_t *frame,
                                      uint8_t source,
                                      uint8_t destination,
                                      uint8_t message_type,
                                      const brrs_beacon_config_t *config)
{
    uint8_t slot;

    memset(frame, 0, BRRS_BEACON_PSDU_BYTES);
    frame[0] = 0xC5U;
    frame[1] = 0x8CU;
    frame[BRRS_IDX_SOURCE] = source;
    frame[BRRS_IDX_DEST] = destination;
    frame[BRRS_IDX_MSG_TYPE] = message_type;
    frame[BRRS_IDX_PROTOCOL_VERSION] = BRRS_PROTOCOL_VERSION;
    brrs_put_u16_le(&frame[BRRS_IDX_SUPERFRAME_SEQ], config->superframe_seq);
    brrs_put_u16_le(&frame[BRRS_BEACON_IDX_PREAMBLE_SYMBOLS],
                    config->data_preamble_symbols);
    brrs_put_u16_le(&frame[BRRS_BEACON_IDX_PSDU_BYTES], config->data_psdu_bytes);
    frame[BRRS_BEACON_IDX_DATA_RATE] = config->data_rate;
    frame[BRRS_BEACON_IDX_ACTIVE_BITMAP] =
        (uint8_t)(config->active_node_bitmap & BRRS_SENSOR_BITMAP_MASK);
    brrs_put_u16_le(&frame[BRRS_BEACON_IDX_FIRST_SLOT_OFFSET_US],
                    config->first_slot_offset_us);
    brrs_put_u16_le(&frame[BRRS_BEACON_IDX_SLOT_INTERVAL_US],
                    config->slot_interval_us);
    brrs_put_u16_le(&frame[BRRS_BEACON_IDX_SUPERFRAME_PERIOD_US],
                    config->superframe_period_us);
    frame[BRRS_BEACON_IDX_SLOT_COUNT] = config->slot_count;
    for (slot = 0U; slot < config->slot_count && slot < BRRS_MAX_DATA_SLOTS; slot++)
    {
        uint8_t *packed = &frame[BRRS_BEACON_IDX_SLOT_OWNERS + slot / 2U];
        uint8_t owner = (uint8_t)(config->slot_owner[slot] & 0x0FU);

        if ((slot & 1U) == 0U)
        {
            *packed = owner;
        }
        else
        {
            *packed |= (uint8_t)(owner << 4);
        }
    }
}

static inline bool brrs_decode_beacon(const uint8_t *frame,
                                      brrs_beacon_config_t *config)
{
    uint8_t slot;

    if (frame[BRRS_IDX_PROTOCOL_VERSION] != BRRS_PROTOCOL_VERSION)
    {
        return false;
    }

    config->superframe_seq = brrs_get_u16_le(&frame[BRRS_IDX_SUPERFRAME_SEQ]);
    config->data_preamble_symbols =
        brrs_get_u16_le(&frame[BRRS_BEACON_IDX_PREAMBLE_SYMBOLS]);
    config->data_psdu_bytes =
        brrs_get_u16_le(&frame[BRRS_BEACON_IDX_PSDU_BYTES]);
    config->data_rate = frame[BRRS_BEACON_IDX_DATA_RATE];
    config->active_node_bitmap =
        (uint8_t)(frame[BRRS_BEACON_IDX_ACTIVE_BITMAP] & BRRS_SENSOR_BITMAP_MASK);
    config->first_slot_offset_us =
        brrs_get_u16_le(&frame[BRRS_BEACON_IDX_FIRST_SLOT_OFFSET_US]);
    config->slot_interval_us =
        brrs_get_u16_le(&frame[BRRS_BEACON_IDX_SLOT_INTERVAL_US]);
    config->superframe_period_us =
        brrs_get_u16_le(&frame[BRRS_BEACON_IDX_SUPERFRAME_PERIOD_US]);
    config->slot_count = frame[BRRS_BEACON_IDX_SLOT_COUNT];
    if (config->slot_count > BRRS_MAX_DATA_SLOTS)
    {
        return false;
    }
    memset(config->slot_owner, 0, sizeof(config->slot_owner));
    for (slot = 0U; slot < config->slot_count; slot++)
    {
        uint8_t packed = frame[BRRS_BEACON_IDX_SLOT_OWNERS + slot / 2U];
        config->slot_owner[slot] = ((slot & 1U) == 0U) ?
            (uint8_t)(packed & 0x0FU) : (uint8_t)(packed >> 4);
    }
    return true;
}

static inline bool brrs_build_round_robin_schedule(brrs_beacon_config_t *config,
                                                    uint8_t repeats)
{
    uint8_t round;
    uint8_t bit;
    uint8_t slot = 0U;
    uint8_t active_count = 0U;

    for (bit = 0U; bit < 7U; bit++)
    {
        if ((config->active_node_bitmap & (uint8_t)(1U << bit)) != 0U)
        {
            active_count++;
        }
    }

    if (repeats == 0U ||
        (uint16_t)active_count * repeats > BRRS_MAX_DATA_SLOTS)
    {
        return false;
    }

    memset(config->slot_owner, 0, sizeof(config->slot_owner));
    for (round = 0U; round < repeats; round++)
    {
        for (bit = 0U; bit < 7U; bit++)
        {
            if ((config->active_node_bitmap & (uint8_t)(1U << bit)) != 0U)
            {
                config->slot_owner[slot++] = (uint8_t)(bit + 2U);
            }
        }
    }
    config->slot_count = slot;
    return true;
}

static inline uint8_t brrs_node_slot_count(const brrs_beacon_config_t *config,
                                           uint8_t node_seq)
{
    uint8_t count = 0U;
    uint8_t slot;

    for (slot = 0U; slot < config->slot_count; slot++)
    {
        if (config->slot_owner[slot] == node_seq)
        {
            count++;
        }
    }
    return count;
}

static inline uint8_t brrs_node_bitmap_bit(uint8_t node_seq)
{
    if (node_seq < 2U || node_seq > 8U)
    {
        return 0U;
    }
    return (uint8_t)(1U << (node_seq - 2U));
}

static inline uint8_t brrs_active_slot_rank(uint8_t active_bitmap,
                                            uint8_t node_seq)
{
    uint8_t rank = 0U;
    uint8_t bit;

    if (node_seq < 2U || node_seq > 8U)
    {
        return 0U;
    }

    for (bit = 0U; bit < (uint8_t)(node_seq - 2U); bit++)
    {
        if ((active_bitmap & (uint8_t)(1U << bit)) != 0U)
        {
            rank++;
        }
    }
    return rank;
}

static inline uint8_t brrs_active_node_count(uint8_t active_bitmap)
{
    uint8_t count = 0U;

    active_bitmap &= BRRS_SENSOR_BITMAP_MASK;
    while (active_bitmap != 0U)
    {
        count += active_bitmap & 1U;
        active_bitmap >>= 1;
    }
    return count;
}

#endif /* BRRS_BEACON_PROTOCOL_H */
